/* 
 1. Normally If-else we used for if there a block of line is there and this if condtions check the value if the condition is ture it return the true or false.

*/

// Conditional statements
 
// let raining = false; // This is an one example  
// let cloudy = false; 

// if(raining || cloudy){
//     console.log("don't forget to take the umberalla");
// }
// else{
//     console.log("It's better day you can go outside");
// }

// 2. Another example 
// Real time hour example 

// let hours = new Date().getHours();

// if(hours >= 0  && hours <= 13 ){
//     console.log("Good Morning");
     
// }
// else if(hours >= 13 && hours <= 17 ){
//     console.log("Good Afternoon");

// }
// else{
//     console.log("Good Evening");
// };


